# Exercises with Python




https://docs.python.org/

https://docs.scipy.org/doc/numpy/




In [1]:
import numpy as np

## Numpy
### Exercise 1


https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.random.randint.html

In [2]:
import numpy as np

# Creating a NumPy array
my_array = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5])




In [3]:
# Sorting the array
sorted_array = np.sort(my_array)
print("Sorted Array:", sorted_array)



Sorted Array: [1 1 2 3 4 5 5 6 9]


In [4]:
# Searching for an element
element_to_search = 5
index = np.where(my_array == element_to_search)[0]
if index.size > 0:
    print(f"Element {element_to_search} found at index {index[0]}")
else:
    print(f"Element {element_to_search} not found in the array")




Element 5 found at index 4


In [5]:
# Adding elements
element_to_add = 7
new_array = np.append(my_array, element_to_add)
print("Array after adding element:", new_array)



Array after adding element: [3 1 4 1 5 9 2 6 5 7]


In [6]:
# Deleting elements
index_to_delete = 2  # Index of element '4'
new_array = np.delete(my_array, index_to_delete)
print("Array after deleting element:", new_array)

Array after deleting element: [3 1 1 5 9 2 6 5]


In [7]:
# Example of set
L = [1,1,2]
type(L)

list

In [8]:
set(L)

{1, 2}

In [9]:
# transformation back to list
L = list(set(L))
L

[1, 2]

In a line of code:

In [10]:
# percentiles
# Define 'no_duplicados' as a NumPy array with data
import numpy as np
no_duplicados = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5])

# Calculate the 25th percentile
percentile_25 = np.percentile(no_duplicados, 25)

# Now, 'percentile_25' contains the 25th percentile of 'no_duplicados'
print(percentile_25)

2.0


#### For this array of non-duplicated elements, add a unit to each element.

In [11]:
x = np.array([-5,6,-7,9])
print(np.absolute(x)) #Abs

[5 6 7 9]


In [12]:
np.zeros((3,5),dtype=float)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

Equally divide into n spaces

In [13]:
x = np.linspace(1,2,5)
x

array([1.  , 1.25, 1.5 , 1.75, 2.  ])